### PR TITLE
README.md: Add NPCAP Related Issue

### PR DESCRIPTION
**Pull request by MasonT8198**
It would be nice to see if we could have binaries that support 1.31 and onward, however I'm not entirely sure how well this will go

### CODE REVIEW

**Comment by MasonT8198** [comment]
I believe I have backported the Windows Infra to compile binaries that are 1.31+ compliant

**Comment by MasonT8198** [comment]
Tested on my machine running npcap 1.31

Would like someone to try it out first before saying it's good to go and I can close this, and try to fix the windows runners speed issues

**Review by codedwrench — COMMENTED** [review]
-

**Comment by codedwrench** [comment]
> It would be nice to see if we could have binaries that support 1.31 and onward, however I'm not entirely sure how well this will go

As far as how well this would go, XLHA 1.1 still worked with the older npcap, if newer npcap versions don't get broken by this, I doubt any change in XLHA would've

**Comment by MasonT8198** [comment]
Pretty sure this works fine now, I still recommend installing npcap 1.60 though, and if we needed to we can use the npcap 1.31 dll anyway

**Pull request closed without merging**
